-- = LISTAR TODO
DELIMITER $$
CREATE PROCEDURE PROC_PRIVILEGIO_LISTAR()
BEGIN
  SELECT * FROM PRIVILEGIO;
END $$
DELIMITER ;



-- = CREAR O MODIFICAR
DELIMITER $$
CREATE PROCEDURE PROC_PRIVILEGIO_CU(
    _ID_PRIVILEGIO INT,
    _DESCRIPCION VARCHAR(30)
) BEGIN
    -- MENSAJE A LA INTERFAZ
    DECLARE __ICON VARCHAR(10) DEFAULT 'error';
    DECLARE __MESSAGE_TEXT VARCHAR(300) DEFAULT 'HA OCURRIDO UN ERROR';
    DECLARE __STATUS_CODE CHAR(3) DEFAULT '501';

    -- COMPROBAR QUE EL NOMBRE NO EXISTA
    DECLARE __EXISTS_NOMBRE INT DEFAULT 0;
    SELECT ID_PRIVILEGIO INTO __EXISTS_NOMBRE
    FROM PRIVILEGIO
    WHERE ID_PRIVILEGIO <> _ID_PRIVILEGIO AND
    DESCRIPCION = _DESCRIPCION AND ESTADO <> 0;


    IF __EXISTS_NOMBRE = 0 THEN
        IF _ID_PRIVILEGIO = 0 THEN
            INSERT INTO PRIVILEGIO
                (DESCRIPCION, ESTADO) VALUES
                (_DESCRIPCION, '1');

                -- MENSAJE
                SET __ICON = 'success';
                SET __MESSAGE_TEXT = 'REGISTRO EXITOSO';
                SET __STATUS_CODE = '201';
        ELSE
            UPDATE PRIVILEGIO
                SET 
                    DESCRIPCION = _DESCRIPCION
                WHERE
                    ID_PRIVILEGIO = _ID_PRIVILEGIO;

                -- MENSAJE
                SET __ICON = 'success';
                SET __MESSAGE_TEXT = 'DATOS ACTUALIZADOS';
                SET __STATUS_CODE = '202';
        END IF;
    ELSE
         -- MENSAJE
        SET __ICON = 'warning';
        SET __MESSAGE_TEXT = '¡EL NOMBRE YA SE ENCUENTRA EN USO!';
        SET __STATUS_CODE = '200';
    END IF;
    SELECT __ICON AS 'ICON', __MESSAGE_TEXT AS 'MESSAGE_TEXT', __STATUS_CODE AS 'STATUS_CODE';
END $$
DELIMITER ;



-- = ELIMINAR PRIVILEGIO
DELIMITER $$
CREATE PROCEDURE PROC_PRIVILEGIO_DELETE(
    _ID_PRIVILEGIO INT
) BEGIN
    -- MENSAJES A LA INTERFAZ
    DECLARE __ICON VARCHAR(10) DEFAULT 'error';
    DECLARE __MESSAGE_TEXT VARCHAR(300) DEFAULT 'HA OCURRIDO UN ERROR';
    DECLARE __STATUS_CODE CHAR(3) DEFAULT '501';

    -- SABER SI NO SE ENCUENTRA O YA ESTA ELIMINADO
    DECLARE __NO_EXISTS INT DEFAULT 0;

    SELECT IF(ESTADO <> 0, ID_PRIVILEGIO, 0) INTO __NO_EXISTS FROM PRIVILEGIO
    WHERE ID_PRIVILEGIO = _ID_PRIVILEGIO;

    IF __NO_EXISTS = 0 THEN 
        -- MENSAJE
        SET __ICON = 'warning';
        SET __MESSAGE_TEXT = 'EL ELEMENTO NO EXISTE O YA HA SIDO ELIMINADO';
        SET __STATUS_CODE = '200';
    ELSE
        UPDATE PRIVILEGIO
            SET ESTADO = '0'
            WHERE ID_PRIVILEGIO = _ID_PRIVILEGIO;
        -- MENSAJE
            SET __ICON = 'success';
            SET __MESSAGE_TEXT = 'ELEMENTO ELIMINADO';
            SET __STATUS_CODE = '202';
    END IF;
    SELECT __ICON AS 'ICON', __MESSAGE_TEXT AS 'MESSAGE_TEXT', __STATUS_CODE AS 'STATUS_CODE';
END $$
DELIMITER ;