-- = LISTAR TODO
DELIMITER $$
CREATE PROCEDURE PROC_PROCEDIMIENTO_LISTAR()
BEGIN
  SELECT * FROM PROCEDIMIENTO;
END $$
DELIMITER ;



-- = CREAR O MODIFICAR
DELIMITER $$
CREATE PROCEDURE PROC_PROCEDIMIENTO_CU(
    _ID_PROCEDIMIENTO  INT,
    _NOM_PROCEDIMIENTO VARCHAR(200),
    _PRECIO DECIMAL(10,2)
) BEGIN
    -- MENSAJE A LA INTERFAZ
    DECLARE __ICON VARCHAR(10) DEFAULT 'error';
    DECLARE __MESSAGE_TEXT VARCHAR(300) DEFAULT 'HA OCURRIDO UN ERROR';
    DECLARE __STATUS_CODE CHAR(3) DEFAULT '501';

    -- COMPROBAR QUE EL NOMBRE NO EXISTA
    DECLARE __EXISTS_NOMBRE INT DEFAULT 0;
    SELECT ID_PROCEDIMIENTO INTO __EXISTS_NOMBRE
    FROM PROCEDIMIENTO
    WHERE ID_PROCEDIMIENTO <> _ID_PROCEDIMIENTO AND
    NOM_PROCEDIMIENTO = _NOM_PROCEDIMIENTO AND ESTADO <> 0;

    IF __EXISTS_NOMBRE = 0 THEN
        IF _ID_PROCEDIMIENTO = 0 THEN
            INSERT INTO PROCEDIMIENTO
                (NOM_PROCEDIMIENTO, PRECIO, ESTADO) VALUES
                (_NOM_PROCEDIMIENTO, _PRECIO, '1');

                -- MENSAJE
                SET __ICON = 'success';
                SET __MESSAGE_TEXT = 'REGISTRO EXITOSO';
                SET __STATUS_CODE = '201';
        ELSE
            UPDATE PROCEDIMIENTO
                SET 
                    NOM_PROCEDIMIENTO = _NOM_PROCEDIMIENTO,
                    PRECIO = _PRECIO
                WHERE
                    ID_PROCEDIMIENTO = _ID_PROCEDIMIENTO;

                -- MENSAJE
                SET __ICON = 'success';
                SET __MESSAGE_TEXT = 'DATOS ACTUALIZADOS';
                SET __STATUS_CODE = '202';
        END IF;
    ELSE
         -- MENSAJE
        SET __ICON = 'warning';
        SET __MESSAGE_TEXT = '¡EL NOMBRE YA SE ENCUENTRA EN USO!';
        SET __STATUS_CODE = '200';
    END IF;
    SELECT __ICON AS 'ICON', __MESSAGE_TEXT AS 'MESSAGE_TEXT', __STATUS_CODE AS 'STATUS_CODE';
END $$
DELIMITER ;


-- = ELIMINAR PROCEDIMIENTO
DELIMITER $$
CREATE PROCEDURE PROC_PROCEDIMIENTO_DELETE(
    _ID_PROCEDIMIENTO INT
) BEGIN
    -- MENSAJES A LA INTERFAZ
    DECLARE __ICON VARCHAR(10) DEFAULT 'error';
    DECLARE __MESSAGE_TEXT VARCHAR(300) DEFAULT 'HA OCURRIDO UN ERROR';
    DECLARE __STATUS_CODE CHAR(3) DEFAULT '501';

    -- SABER SI NO SE ENCUENTRA O YA ESTA ELIMINADO
    DECLARE __NO_EXISTS INT DEFAULT 0;

    SELECT IF(ESTADO <> 0, ID_PROCEDIMIENTO, 0) INTO __NO_EXISTS FROM PROCEDIMIENTO
    WHERE ID_PROCEDIMIENTO = _ID_PROCEDIMIENTO;

    IF __NO_EXISTS = 0 THEN 
        -- MENSAJE
        SET __ICON = 'warning';
        SET __MESSAGE_TEXT = 'EL ELEMENTO NO EXISTE O YA HA SIDO ELIMINADO';
        SET __STATUS_CODE = '200';
    ELSE
        UPDATE PROCEDIMIENTO
            SET ESTADO = '0'
            WHERE ID_PROCEDIMIENTO = _ID_PROCEDIMIENTO;
        -- MENSAJE
            SET __ICON = 'success';
            SET __MESSAGE_TEXT = 'ELEMENTO ELIMINADO';
            SET __STATUS_CODE = '202';
    END IF;
    SELECT __ICON AS 'ICON', __MESSAGE_TEXT AS 'MESSAGE_TEXT', __STATUS_CODE AS 'STATUS_CODE';
END $$
DELIMITER ;