-- = LISTAR TODO
DELIMITER $$
CREATE PROCEDURE PROC_CLIENTE_LISTAR()
BEGIN
  SELECT * FROM CLIENTE;
END $$
DELIMITER ;



-- = CREAR O MODIFICAR
DELIMITER $$
CREATE PROCEDURE PROC_CLIENTE_CU(
    _ID_CLIENTE INT,
    _DOCUMENTO CHAR(8),
    _NOMBRES VARCHAR(100),
    _APMATERNO VARCHAR(50),
    _APPATERNO VARCHAR (50),
    _CELULAR CHAR(9)
) BEGIN
    -- MENSAJE A LA INTERFAZ
    DECLARE __ICON VARCHAR(10) DEFAULT 'error';
    DECLARE __MESSAGE_TEXT VARCHAR(300) DEFAULT 'HA OCURRIDO UN ERROR';
    DECLARE __STATUS_CODE CHAR(3) DEFAULT '501';

    -- COMPROBAR QUE EL NOMBRE NO EXISTA
    DECLARE __EXISTS_NOMBRE INT DEFAULT 0;
    SELECT ID_CLIENTE INTO __EXISTS_NOMBRE
    FROM CLIENTE
    WHERE ID_CLIENTE <> _ID_CLIENTE AND
    DOCUMENTO = _DOCUMENTO AND ESTADO <> 0;


    IF __EXISTS_NOMBRE = 0 THEN
        IF _ID_CLIENTE = 0 THEN
            INSERT INTO CLIENTE
                (DOCUMENTO, NOMBRES, APMATERNO, APPATERNO, CELULAR, ESTADO) VALUES
                (_DOCUMENTO, _NOMBRES, _APMATERNO, _APPATERNO, _CELULAR, '1');

                -- MENSAJE
                SET __ICON = 'success';
                SET __MESSAGE_TEXT = 'REGISTRO EXITOSO';
                SET __STATUS_CODE = '201';
        ELSE
            UPDATE CLIENTE
                SET 
                    DOCUMENTO = _DOCUMENTO,
                    NOMBRES = _NOMBRES,
                    APMATERNO = _APMATERNO,
                    APPATERNO = _APPATERNO,
                    CELULAR = _CELULAR
                WHERE
                    ID_CLIENTE = _ID_CLIENTE;

                -- MENSAJE
                SET __ICON = 'success';
                SET __MESSAGE_TEXT = 'DATOS ACTUALIZADOS';
                SET __STATUS_CODE = '202';
        END IF;
    ELSE
         -- MENSAJE
        SET __ICON = 'warning';
        SET __MESSAGE_TEXT = '¡EL NOMBRE YA SE ENCUENTRA EN USO!';
        SET __STATUS_CODE = '200';
    END IF;
    SELECT __ICON AS 'ICON', __MESSAGE_TEXT AS 'MESSAGE_TEXT', __STATUS_CODE AS 'STATUS_CODE';
END $$
DELIMITER ;



-- = ELIMINAR CLIENTE
DELIMITER $$
CREATE PROCEDURE PROC_CLIENTE_DELETE(
    _ID_CLIENTE INT
) BEGIN
    -- MENSAJES A LA INTERFAZ
    DECLARE __ICON VARCHAR(10) DEFAULT 'error';
    DECLARE __MESSAGE_TEXT VARCHAR(300) DEFAULT 'HA OCURRIDO UN ERROR';
    DECLARE __STATUS_CODE CHAR(3) DEFAULT '501';

    -- SABER SI NO SE ENCUENTRA O YA ESTA ELIMINADO
    DECLARE __NO_EXISTS INT DEFAULT 0;

    SELECT IF(ESTADO <> 0, ID_CLIENTE, 0) INTO __NO_EXISTS FROM CLIENTE
    WHERE ID_CLIENTE = _ID_CLIENTE;

    IF __NO_EXISTS = 0 THEN 
        -- MENSAJE
        SET __ICON = 'warning';
        SET __MESSAGE_TEXT = 'EL ELEMENTO NO EXISTE O YA HA SIDO ELIMINADO';
        SET __STATUS_CODE = '200';
    ELSE
        UPDATE CLIENTE
            SET ESTADO = '0'
            WHERE ID_CLIENTE = _ID_CLIENTE;
        -- MENSAJE
            SET __ICON = 'success';
            SET __MESSAGE_TEXT = 'ELEMENTO ELIMINADO';
            SET __STATUS_CODE = '202';
    END IF;
    SELECT __ICON AS 'ICON', __MESSAGE_TEXT AS 'MESSAGE_TEXT', __STATUS_CODE AS 'STATUS_CODE';
END $$
DELIMITER ;